name: venepagos
description: SDK oficial de Venepagos para Flutter. Integra fácilmente pagos con ventana emergente y callbacks.
version: 1.0.1
homepage: https://venepagos.com.ve
repository: https://github.com/marioagutierrez/flutter-venepagos

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  http: ^1.1.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
